config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'top#index'
  get "/atfirst" => "atfirst#atfirst"

  resources :users, only: [:index, :show] do
    member do
      get :favorite_users
      get :favorite_phrases
      get :themes
    end
    collection do
      get :mypage
    end
  end
  resources :phrases do
    resources :comments, only: [:create, :destroy]
  end
  resources :themes do
    resources :theme_comments, only: [:create, :destroy]
  end
  resource :favorite_users, only: [:create, :destroy]
  resource :favorite_phrases, only: [:create, :destroy]

  get '/search' => 'search#search'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    root "top#index"
    resources :users, only: [:index, :destroy]
    resources :phrases, only: [:index, :show, :destroy]
    resources :themes, only: [:index, :show, :destroy]
  end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @users = User.includes(:likers).sort {|a,b| b.likers.size <=> a.likers.size}
    @phrases = Phrase.includes(:likers).sort {|a,b| b.likers.size <=> a.likers.size}
    @themes = Theme.limit(4).order("created_at DESC")
    @tag = Phrase.pluck(:tag_1, :tag_2, :tag_3).flatten.uniq #pcluckでtagをまとめflattenで二次元配列を解除。uniqで重複を削除。
  end
end

app/views/top/index.html.erb
<div class="bg-white p-3">
<% unless user_signed_in? %>
<div class="border rounded-3 p-3" style="background-color:lightblue;">
  <p>はじめての方へ => <%= link_to "お読みください。", atfirst_path %></p>
  <p>ゲストユーザーでログイン可能です。 => <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %></p>
  <p><%= link_to "会員登録", new_user_registration_path %>してギターフレーズを投稿しませんか？ =>もしくは<%= link_to "ログイン", new_user_session_path %></p>
</div>
<% end %>

<p class="title mt-3 mb-3"><%= image_pack_tag "guitar.svg", alt: "guitar", size: "28x28", class: "d-inline-block me-1" %>人気のフレーズ</p>

<div class="row">
  <% @phrases.first(4).each do |phrase| %>
    <div class="col-sm-6 mb-5">
      <div class="text-center">
      <%= fav_user_only_link?(phrase, phrase.title) %><%= image_pack_tag "lock-fill.svg" if phrase.user_only? %>
      
      <p class="text-muted mb-0"><%= phrase.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
      <div class="d-flex justify-content-center mb-2">
        <%= fav_user_only?(phrase)%>
      </div>
      <div class="d-flex justify-content-center">[投稿者]<%= link_to phrase.user.username, user_path(phrase.user), class: "me-1 text-dark" %> good(<%= phrase.likers.count %>)</div>
    </div>
  <% end %>
</div>

<%= link_to "全てのフレーズを見る", phrases_path, class: "d-flex justify-content-end" %>
<p class="title mt-3 mb-3"><%= image_pack_tag "music.svg", alt: "music", size: "28x28", class: "d-inline-block me-1" %>テーマ</p>

<div class="row">
  <% @themes.each do |theme| %>
    <div class="col-sm-6 mb-5">
      <div class="text-center">
      <%= link_to theme.title, theme_path(theme), class: "text-dark" %>
      
      <p class="text-muted mb-0"><%= theme.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
      <div class="d-flex justify-content-center mb-2">
        <%= audio_tag url_for(theme.music_file), controls: true, controlslist: "nodownload" %>
      </div>
      <div class="d-flex justify-content-center">[投稿者]<%= link_to theme.user.username, user_path(theme.user), class: "text-dark" %></div>
    </div>
  <% end %>
</div>

<%= link_to "全てのテーマを見る", themes_path, class: "d-flex justify-content-end" %>
<p class="title mt-3 mb-3"><%= image_pack_tag "tag.svg", alt: "tag", size: "28x28", class: "d-inline-block me-1" %>タグ</p>
    <div class="p-2">
    <% @tag.each do |t| %>
      <% if t.present? %>
        <%= link_to t, search_path(search: {model: "phrase", value: t}), class: "d-inline-block btn btn-secondary btn-sm text-white text-decoration-none m-1" %>
      <% end %>
    <% end %>
    </div>
<p class="title mt-3 mb-3"><%= image_pack_tag "people-fill.svg", alt: "users", size: "28x28", class: "d-inline-block me-1" %>人気のユーザー</p>
<%= render "layouts/user_list", users: @users%>
<%= link_to "全てのユーザーを見る", users_path, class: "d-flex justify-content-end" %>
</div>