config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'top#index'
  get "/atfirst" => "atfirst#atfirst"

  resources :users, only: [:index, :show] do
    member do
      get :favorite_users
      get :favorite_phrases
      get :themes
    end
    collection do
      get :mypage
    end
  end
  resources :phrases do
    resources :comments, only: [:create, :destroy]
  end
  resources :themes do
    resources :theme_comments, only: [:create, :destroy]
  end
  resource :favorite_users, only: [:create, :destroy]
  resource :favorite_phrases, only: [:create, :destroy]

  get '/search' => 'search#search'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    root "top#index"
    resources :users, only: [:index, :destroy]
    resources :phrases, only: [:index, :show, :destroy]
    resources :themes, only: [:index, :show, :destroy]
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  has_many :theme_comments, dependent: :destroy
  has_many :theme_commented_by, through: :theme_comments, source: :user

  has_one_attached :music_file
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :overview, presence: true, length: { maximum: 1000 }
  validate :music_file_presence, on: :create
  with_options length: { maximum: 30 } do
    validates :tag_1
    validates :tag_2
    validates :tag_3
  end
  
  #音声ファイルが空じゃないかと、ファイルの拡張子をチェックする
  def music_file_presence
    if music_file.attached?
      unless music_file.content_type.in?(ALLOWED_MUSIC_TYPES)
        errors.add(:music_file, :invalid_music_type)
      end
    else
      errors.add(:music_file, 'を添付してください')
    end
  end
end

app/controllers/admin/themes_controller.rb
class Admin::ThemesController < Admin::Base
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to :admin_themes, notice: "テーマを削除しました。"
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @themes = Theme.page(params[:page]).per(6).order('created_at DESC')
  end

  def show
    @theme = Theme.find(params[:id])
    @theme_comment = ThemeComment.new
    @theme_comments = @theme.theme_comments.all.order("created_at DESC")
  end

  def new
    @theme = current_user.themes.build
  end

  def create
    @theme = current_user.themes.build(theme_params)
    if @theme.save
      redirect_to @theme, notice: "テーマを投稿しました。"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
      redirect_to @theme, notice: "テーマを更新しました。"
    else
      render "new"
    end
  end

  def destroy
    @theme.destroy
    redirect_to user_path(current_user), notice: "テーマを削除しました。"
  end

  private

  def theme_params
    params.require(:theme).permit(
      :music_file,
      :title,
      :overview,
      :tag_1,
      :tag_2,
      :tag_3,
    )
  end

  def correct_user
    @theme = current_user.themes.find_by(id: params[:id])
    unless @theme
      redirect_to root_url
    end
  end
end

app/views/themes/_themes.html.erb
<% themes.each do |t| %>
<div class="border-bottom">
  <div class="row pt-3 pb-3">
    <div class="col-sm-8">
      <div class="row">
        <div class="col-3 d-flex justify-content-center align-items-center">
          <%= cheak_use_picture(t.user, "124x124") %>
        </div>
        <div class="col-9">
          <div class="mb-2">
            <h6 class="d-inline-block"><%= link_to t.user.username, user_path(t.user), class: "text-dark" %></h6> <%= t.created_at.strftime("%Y-%m-%d %H:%M")%>
          </div>
          <div class="pt-3 pb-3">
            <h3><%= image_pack_tag "music.svg", alt: "music", size: "28x28", class: "d-inline-block" %><%= link_to t.title, theme_path(t), class: "text-dark d-inline-block p-3" %></h3>
          </div>
          <div>
          <%= image_pack_tag "tag.svg", alt: "tag" %>
            <%= link_to t.tag_1, search_path(search: {model: "theme", value: t.tag_1}), class: "text-dark" %>
            <%= link_to t.tag_2, search_path(search: {model: "theme", value: t.tag_2}), class: "text-dark" %>
            <%= link_to t.tag_3, search_path(search: {model: "theme", value: t.tag_3}), class: "text-dark" %>

          </div>
          <div>
            <%= link_to "詳しく見る", theme_path(t), class: "text-dark" %> コメント(<%= t.theme_commented_by.count %>)
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4 d-flex align-items-center">
      <%= audio_tag url_for(t.music_file), controls: true, controlslist: "nodownload" %>
    </div>
  </div>
</div>
<% end %>

app/views/themes/edit.html.erb
<% @page_title = "テーマ編集" %>

<h2><%= @page_title %></h2>

<%= form_with(model: @theme) do |t| %>
  <%= render "layouts/error_messages", model: t.object %>

    <div class="field mb-3">
      <%= audio_tag url_for(@theme.music_file), controls: true, controlslist: "nodownload" %>
    </div>

  <div class="field mb-3">
    <%= t.label :title, "タイトル" %>
    <%= t.text_field :title, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= t.label :overview, "テーマ概要" %>
    <%= t.text_area :overview, rows: 6, class: "form-control" %>
  </div>

  <%= t.label :tag_1, "タグ(3つまで登録可能)" %>
  <div class="row mb-3">
    <div class="col-sm-2">
      
      <%= t.text_field :tag_1, class: "form-control", size: 10 %>
    </div>
    <div class="col-sm-2">
      <% t.label :tag_2 %>
      <%= t.text_field :tag_2, class: "form-control", size: 10 %>
    </div>
    <div class="col-sm-2">
      <% t.label :tag_3 %>
      <%= t.text_field :tag_3, class: "form-control", size: 10 %>
    </div>
  </div>
  
  <div class="actions mb-3">
    <%= t.submit "編集", class: "btn btn-primary" %>
  </div>
  
  <%= link_to "Back", :back %>
<div class="border-bottom mt-5"></div>
<% end %>

app/views/themes/index.html.erb
<% @page_title = "テーマ一覧" %>

<div class="bg-white p-3">
  <h2 class="text-center"><%= image_pack_tag "music.svg", alt: "music", size: "28x28", class: "d-inline-block" %><%= @page_title %><%= image_pack_tag "music.svg", alt: "music", size: "28x28", class: "d-inline-block" %></h2>
  
  <%= render "themes", themes: @themes %>
  <div class="mt-3">
  <%= paginate @themes %>
  </div>
</div>

app/views/themes/new.html.erb
<% @page_title = "テーマ投稿" %>

<h2><%= @page_title %></h2>

<%= form_with(model: @theme) do |t| %>
  <%= render "layouts/error_messages", model: t.object %>

  <div class="field mt-3 mb-3">
    <%= t.label :music_file, "音声ファイル(MP3,WAV,FLAC,OGG)" %>
    <div><%= t.file_field :music_file %></div>
  </div>

  <div class="field mb-3">
    <%= t.label :title, "タイトル" %>
    <%= t.text_field :title, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= t.label :overview, "概要" %>
    <%= t.text_area :overview, rows: 6, placeholder:"コード進行や演奏時のポイントを書いてみましょう", class: "form-control" %>
  </div>

  <%= t.label :tag_1, "タグ(3つまで登録可能)" %>
  <div class="row mb-3">
    <div class="col-sm-2">
      
      <%= t.text_field :tag_1, class: "form-control", size: 10 %>
    </div>
    <div class="col-sm-2">
      <% t.label :tag_2 %>
      <%= t.text_field :tag_2, class: "form-control", size: 10 %>
    </div>
    <div class="col-sm-2">
      <% t.label :tag_3 %>
      <%= t.text_field :tag_3, class: "form-control", size: 10 %>
    </div>
  </div>
  
  <div class="actions mb-3">
    <%= t.submit "投稿", class: "btn btn-primary" %>
  </div>
  
  <%= link_to "Back", :back %>
<div class="border-bottom mt-5"></div>
<% end %>

app/views/themes/show.html.erb
  <% @page_title = @theme.title %>

<div class="container bg-white mb-4 pt-3 pb-4">
    <div class="d-flex justify-content-center align-items-baseline mb-3 small">
        <%= cheak_use_picture(@theme.user, "32x32") %>&nbsp;
        <%= link_to @theme.user.username, user_path(@theme.user), class: "text-dark" %>&nbsp;<%= @theme.created_at.strftime("%Y-%m-%d %H:%M") %>に作成
    </div>
  <h3 class="d-flex align-items-center justify-content-center"><%= @theme.title %></h3>
</div>

<div class="rounded bg-white p-3 mb-4">
<div class="d-flex justify-content-start mb-2"><h5><u>テーマ</u></h5></div>
  <div class="d-flex justify-content-center mb-2">
    <%= audio_tag url_for(@theme.music_file), controls: true, controlslist: "nodownload" %>
  </div>
  <div class="d-flex justify-content-center">
    <% unless user_signed_in? %>
      <p><%= link_to "会員登録", new_user_registration_path %>してテーマをダウンロード</p>
    <% else %>
      <%= link_to "ダウンロード", rails_blob_path(@theme.music_file), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

  <div class="rounded bg-white p-3 mb-4">
    <div class="d-flex justify-content-start mb-2"><h5><u>概要</u></h5></div>
      <div class="mb-3 p-2"><%= convert_url_into_a_tag(h(simple_format(@theme.overview))).html_safe %></div>
      <div class="p-2">
        <%= image_pack_tag "tag.svg", alt: "tag" %>
          <%= link_to @theme.tag_1, search_path(search: {model: "theme", value: @theme.tag_1}), class: "text-dark" %>
          <%= link_to @theme.tag_2, search_path(search: {model: "theme", value: @theme.tag_2}), class: "text-dark" %>
          <%= link_to @theme.tag_3, search_path(search: {model: "theme", value: @theme.tag_3}), class: "text-dark" %>
      </div>
      <% if current_user == @theme.user %>
        <%= link_to image_pack_tag("pencil-square.svg", alt: "edit"), edit_theme_path(@theme), class: "me-2" %>
        <%= link_to image_pack_tag("trash.svg", alt: "delete"), @theme, method: :delete, data: { confirm: "テーマを削除しますか？" }, class: "me-2" %>
      <% end %>
  </div>

  <div class="rounded bg-white p-3 mb-4">
    <div class="d-flex justify-content-start mb-2"><h5><u>コメント(<%= @theme.theme_commented_by.count %>)</u></h5></div>

    <div class="mb-3">
      <% if user_signed_in? %>
        <%= render partial: 'theme_comments/form', locals: { theme_comment: @theme_comment, theme: @theme } %>
      <% else %>
          <div class="d-flex justify-content-center mt-4 mb-4">※ログインすることでコメントできます。</div>
      <% end %>
    </div>
      <% if @theme_comments %>
        <div class="comments_index">
          <div id='comments_area'>
            <%= render partial: 'theme_comments/index', locals: { theme_comments: @theme_comments } %>
          </div>
        </div>
      <% else %>
        コメントはまだありません。
      <% end %>
  </div>