config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'top#index'
  get "/atfirst" => "atfirst#atfirst"

  resources :users, only: [:index, :show] do
    member do
      get :favorite_users
      get :favorite_phrases
      get :themes
    end
    collection do
      get :mypage
    end
  end
  resources :phrases do
    resources :comments, only: [:create, :destroy]
  end
  resources :themes do
    resources :theme_comments, only: [:create, :destroy]
  end
  resource :favorite_users, only: [:create, :destroy]
  resource :favorite_phrases, only: [:create, :destroy]

  get '/search' => 'search#search'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    root "top#index"
    resources :users, only: [:index, :destroy]
    resources :phrases, only: [:index, :show, :destroy]
    resources :themes, only: [:index, :show, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :omniauthable, :recoverable, omniauth_providers: %i[twitter google_oauth2]

  validates :username, presence: true, length: { maximum: 50 }
  validates :introduction, length: { maximum: 200 }
  validate if: :new_profile_picture do
    if new_profile_picture.respond_to?(:content_type)
      unless new_profile_picture.content_type.in?(ALLOWED_CONTENT_TYPES)
        errors.add(:new_profile_picture, :invalid_image_type)
      end
    else
      errors.add(:new_profile_picture, :invalid)
    end
  end

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    elsif remove_profile_picture
    self.profile_picture.purge
    end
  end

  has_one_attached :profile_picture
  attribute :new_profile_picture
  attribute :remove_profile_picture, :boolean

  #プロフィール編集でパスワード入力なしで編集完了ができるようにする
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  #SNS認証でログインした場合、ユーザー情報を登録する
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.password_manually_updated = true
    end
  end
    
  has_many :phrases, dependent: :destroy
  has_many :themes, dependent: :destroy
  has_many :favorite_users, dependent: :destroy
  has_many :liking_users, through: :favorite_users, source: :fav_user
  has_many :revers_of_favorite_users, class_name: "FavoriteUser", foreign_key: "fav_user_id", dependent: :destroy
  has_many :likers, through: :revers_of_favorite_users, source: :user
  has_many :favorite_phrases, dependent: :destroy
  has_many :liking_phrases, through: :favorite_phrases, source: :phrase
  has_many :comments, dependent: :destroy
  has_many :theme_comments, dependent: :destroy

  #fav関連
  def favorite_user(other_user)
    unless self == other_user
      self.favorite_users.find_or_create_by(fav_user_id: other_user.id)
    end
  end

  def favorite_phrase(other_phrase)
    self.favorite_phrases.find_or_create_by(phrase_id: other_phrase.id)
  end

  def unfavorite_user(other_user)
    fav = self.favorite_users.find_by(fav_user_id: other_user.id) 
    fav.destroy if fav
  end

  def unfavorite_phrase(other_phrase)
    fav = self.favorite_phrases.find_by(phrase_id: other_phrase.id)
    fav.destroy if fav
  end

  #favしているかの確認
  def liking_user?(other)
    self.liking_users.include?(other)
  end

  def liking_phrase?(other)
    self.liking_phrases.include?(other)
  end

  #マイページ用　自分のフレーズとfavユーザーのフレーズをまとめる
  def feed_phrases
    Phrase.where(user_id: self.liking_user_ids + [self.id])
  end

  #ゲストログイン機能 sessions_controllerでゲストログイン処理
  def self.guest
    find_or_create_by(email: "test@com") do |user|
      user.password = "password"
      user.username = "ゲスト"
      user.password_manually_updated = true
      str = "ギタフレ！をご覧いただきありがとうございます。
      GitHubにて使用技術等を掲載しておりますので、ご覧頂ければ幸いです。
      https://github.com/zwgssu/GuitaPhre"
      user.introduction = str.gsub(/(\\r\\n|\\r|\\n)/, "\n")
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :admin_users, notice: "ユーザーを削除しました。"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def twitter
    callback_for(:twitter)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    mypage_users_path
  end
  

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to mypage_users_path, notice: "ログイン完了！ごゆっくりサイトを散策してください！"
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage]
  def index
    @users = User.page(params[:page]).per(20).order('created_at DESC')
  end

  def show
    @user = User.find(params[:id])
    @phrases = @user.phrases.page(params[:page]).per(3).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def favorite_users
    @user = User.find(params[:id])
    @users = @user.liking_users.page(params[:page]).per(6).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def favorite_phrases
    @user = User.find(params[:id])
    @phrases = @user.liking_phrases.page(params[:page]).per(3).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def themes
    @user = User.find(params[:id])
    @themes = @user.themes.page(params[:page]).per(3).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def mypage
    @user = current_user
    @phrases = @user.feed_phrases.page(params[:page]).per(6).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/users/_user_favorite_users.html.erb
<ul class="nav nav-tabs">
 <% if @user == current_user %>
  <li class="nav-item">
    <%= link_to "マイページ", mypage_users_path, class: "nav-link" %>
  </li>
<% end %>
  <li class="nav-item">
  <a href=<%= user_path(@user) %> class="nav-link">フレーズ(<%= @user.phrases.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= themes_user_path(@user) %> class="nav-link">テーマ(<%= @user.themes.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= favorite_phrases_user_path(@user) %> class="nav-link">goodしたフレーズ(<%= @user.liking_phrases.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= favorite_users_user_path(@user) %> class="nav-link active">お気に入りユーザー(<%= @user.liking_users.count %>)</a>
  </li>
</ul>
<div class="contaier border-start border-end border-bottom bg-white p-3">
<% if @users.present? %>
  <div class="row p-3">
  <% @users.each do |user| %>
    <div class="col-md-6 mb-4">
      <div class="row">
          <div class="col-3 d-flex justify-content-end">
            <%= cheak_use_picture(user, "64x64") %>
          </div>
          <div class="col-9">
            <%= link_to user.username, user_path(user) %><br>
            <% if user.introduction.present? %>
              <%= truncate(user.introduction, length: 40) %>
            <% else %>
              自己紹介はありません。
            <% end %>
          </div>
      </div>
    </div>
  <% end %>
  </div>
<% else %>
<p>favしたユーザーはいません。</p>
<% end %>

</div>

<div class="question-index">
  <%= paginate @users, remote: true %>
</div>

app/views/users/_user_head.html.erb
<div class="row mb-3">
  <div class="col-3 d-flex justify-content-center">
    <%= cheak_use_picture(@user, "200x200") %>
  </div>
  <div class="col-9 bg-white p-3">
    <div class="border-bottom mb-2"><h2 class="d-inline-block"><%= @user.username %></h2>
      <% if user_signed_in? %>
        <span id="fav_buttons_<%= @user.id %>"><%= render "favorite_users/fav", user: @user %></span>
      <% else %>
        Fav!(<%= @user.likers.count %>)
      <% end %>

    </div>
    <% if @user.introduction.present? %>
      <%= convert_url_into_a_tag(h(simple_format(@user.introduction))).html_safe %>
    <% else %>
      自己紹介はありません。
    <% end %>
  <div class="d-flex justify-content-end">
  </div>
  </div>
</div>

app/views/users/_user_phrases.html.erb
<ul class="nav nav-tabs">
 <% if @user == current_user %>
  <li class="nav-item">
    <%= link_to "マイページ", mypage_users_path, class: "nav-link" %>
  </li>
<% end %>
  <li class="nav-item">
  <a href=<%= user_path(@user) %> class="nav-link active">フレーズ(<%= @user.phrases.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= themes_user_path(@user) %> class="nav-link">テーマ(<%= @user.themes.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= favorite_phrases_user_path(@user) %> class="nav-link">goodしたフレーズ(<%= @user.liking_phrases.count %>)</a>
  </li>
  <li class="nav-item">
    <a href=<%= favorite_users_user_path(@user) %> class="nav-link">お気に入りユーザー(<%= @user.liking_users.count %>)</a>
  </li>
</ul>
<div class="contaier border-start border-end border-bottom bg-white p-3">
  <% if @phrases.present? %>
  <% @phrases.each do |f| %>
  <div class="border-bottom">
    <div class="row pt-3 pb-3">
      <div class="col-sm-8">
        <div class="row">
          <div class="col-3 d-flex justify-content-center align-items-center">
            <%= cheak_use_picture(f.user, "124x124") %>
          </div>
          <div class="col-9">
            <div class="mb-2">
              <h6 class="d-inline-block"><%= link_to f.user.username, user_path(f.user), class: "text-dark" %></h6> <%= f.created_at.strftime("%Y-%m-%d %H:%M")%> <%= image_pack_tag "lock-fill.svg" if f.user_only? %>
            </div>
            <div class="pt-3 pb-3">
              <h3><%= image_pack_tag "guitar.svg", alt: "guitar", size: "28x28", class: "d-inline-block" %><%= fav_user_only_link?(f, f.title) %></h3>
            </div>
            <div>
            <%= image_pack_tag "tag.svg", alt: "tag" %>
              <%= link_to f.tag_1, search_path(search: {model: "phrase", value: f.tag_1}), class: "text-dark" %>
              <%= link_to f.tag_2, search_path(search: {model: "phrase", value: f.tag_2}), class: "text-dark" %>
              <%= link_to f.tag_3, search_path(search: {model: "phrase", value: f.tag_3}), class: "text-dark" %>

            </div>
            <div>
              <%= fav_user_only_link?(f, "詳しく見る") %> good(<%= f.likers.count %>) コメント(<%= f.commented_by.count %>)
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4 d-flex align-items-center">

        <%= fav_user_only?(f)%>

      </div>
    </div>
  </div>
  <% end %>
  <% else %>
  <p>フレーズはありません。</p>
  <% end%>

</div>

<div class="question-index">
  <%= paginate @phrases, remote: true %>
</div>

app/views/users/favorite_phrases.html.erb
<% @page_title = "goodしたフレーズ" %>

<%= render "user_head" %>

<div id="show_pagenate">
  <%= render partial: 'user_favorite_phrases' %>
</div>

app/views/users/favorite_phrases.js.erb
$('#show_pagenate').html("<%= escape_javascript(render 'user_favorite_phrases') %>");

app/views/users/favorite_users.html.erb
<% @page_title = @user.username + "のお気に入りユーザー" %>

<%= render "user_head" %>

<div id="show_pagenate">
  <%= render partial: 'user_favorite_users' %>
</div>

app/views/users/favorite_users.js.erb
$('#show_pagenate').html("<%= escape_javascript(render 'user_favorite_users') %>");

app/views/users/index.html.erb
<% @page_title = "ユーザー一覧" %>
<div class="bg-white p-3">
<h1 class="text-center mb-1"><%= @page_title %></h1>
  <%= render "layouts/user_list", users: @users %>
  <div class="mt-3">
  <%= paginate @users %>
  </div>
</div>

app/views/users/mypage.html.erb
<% @page_title = "マイページ" %>

<%= render "user_head" %>

<div id="show_pagenate">
  <%= render partial: 'user_mypage' %>
</div>

app/views/users/mypage.js.erb
$('#show_pagenate').html("<%= escape_javascript(render 'user_mypage') %>");

app/views/users/show.html.erb
<% @page_title = @user.username + "のフレーズ" %>
<%= render "user_head" %>

<div id="show_pagenate">
  <%= render partial: 'user_phrases' %>
</div>

app/views/users/show.js.erb
$('#show_pagenate').html("<%= escape_javascript(render 'user_phrases') %>");

app/views/users/themes.html.erb
<% @page_title = @user.username + "のテーマ" %>

<%= render "user_head" %>

<div id="show_pagenate">
  <%= render partial: 'user_themes' %>
</div>

app/views/users/themes.js.erb
$('#show_pagenate').html("<%= escape_javascript(render 'user_themes') %>");