config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  root 'top#index'
  get "/atfirst" => "atfirst#atfirst"

  resources :users, only: [:index, :show] do
    member do
      get :favorite_users
      get :favorite_phrases
      get :themes
    end
    collection do
      get :mypage
    end
  end
  resources :phrases do
    resources :comments, only: [:create, :destroy]
  end
  resources :themes do
    resources :theme_comments, only: [:create, :destroy]
  end
  resource :favorite_users, only: [:create, :destroy]
  resource :favorite_phrases, only: [:create, :destroy]

  get '/search' => 'search#search'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    root "top#index"
    resources :users, only: [:index, :destroy]
    resources :phrases, only: [:index, :show, :destroy]
    resources :themes, only: [:index, :show, :destroy]
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  has_many :theme_comments, dependent: :destroy
  has_many :theme_commented_by, through: :theme_comments, source: :user

  has_one_attached :music_file
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :overview, presence: true, length: { maximum: 1000 }
  validate :music_file_presence, on: :create
  with_options length: { maximum: 30 } do
    validates :tag_1
    validates :tag_2
    validates :tag_3
  end
  
  #音声ファイルが空じゃないかと、ファイルの拡張子をチェックする
  def music_file_presence
    if music_file.attached?
      unless music_file.content_type.in?(ALLOWED_MUSIC_TYPES)
        errors.add(:music_file, :invalid_music_type)
      end
    else
      errors.add(:music_file, 'を添付してください')
    end
  end
end

app/controllers/admin/themes_controller.rb
class Admin::ThemesController < Admin::Base
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to :admin_themes, notice: "テーマを削除しました。"
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @themes = Theme.page(params[:page]).per(6).order('created_at DESC')
  end

  def show
    @theme = Theme.find(params[:id])
    @theme_comment = ThemeComment.new
    @theme_comments = @theme.theme_comments.all.order("created_at DESC")
  end

  def new
    @theme = current_user.themes.build
  end

  def create
    @theme = current_user.themes.build(theme_params)
    if @theme.save
      redirect_to @theme, notice: "テーマを投稿しました。"
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
      redirect_to @theme, notice: "テーマを更新しました。"
    else
      render "new"
    end
  end

  def destroy
    @theme.destroy
    redirect_to user_path(current_user), notice: "テーマを削除しました。"
  end

  private

  def theme_params
    params.require(:theme).permit(
      :music_file,
      :title,
      :overview,
      :tag_1,
      :tag_2,
      :tag_3,
    )
  end

  def correct_user
    @theme = current_user.themes.find_by(id: params[:id])
    unless @theme
      redirect_to root_url
    end
  end
end

app/views/admin/themes/index.html.erb
<% @page_title = "テーマ管理" %>
<div class="container bg-white p-3">
<h3 class="mb-3">テーマ管理</h3>
<ul>
  <% @themes.each do |t| %>
    <li>id:<%= link_to t.id, admin_theme_path(t), target: :_blank, rel: "noopener noreferrer" %> - <%= t.title %> - by<%= link_to t.user.username, user_path(t.user) %> - <%= link_to "削除", admin_theme_path(t), method: :delete, data: { confirm: "このフレーズを削除しますか？" } %></li>
  <% end %>
</ul>
<%= link_to "Back", :admin_root %>

</div>

app/views/admin/themes/show.html.erb
<% @page_title = "テーマ管理" %>
<div class="container bg-white p-3">
<h3 class="mb-3">テーマ管理</h3>
<p><%= link_to @theme.user.username, user_path(@theme.user) %>　の投稿</p>
<p>title: <%= @theme.title %></p>
<div>
<%= audio_tag url_for(@theme.music_file), controls: true %>
</div>
<p>body:</p>
<p><%= convert_url_into_a_tag(h(simple_format(@theme.overview))).html_safe %></p>
<br>
<%= link_to "削除", admin_theme_path(@theme), method: :delete, data: { confirm: "このテーマを削除しますか？" } %>

</div>